### ISSUE TITLE
Portfolio issue 

### ISSUE THREAD

**Issue by Alzubair98** [Leon-Espitia/Portfolio-project-set-up-and-mobile-version-skeleton#4]
you are doing great job 
your code is good and clean 💯💯💯💯

but you can improve it more:
1- please don't leave empty spaces between elements in CSS file
2- kindly add some margin-top to the contact me section to give it some space from the other sections 
3- I'm sure you can do it 😀😀😀

**Comment by Leon-Espitia** [comment]
Thank´s for your recommendations and I would kindly attend to them.
